BEGIN;

-- =========================================================
-- 01_schema.sql
-- Database schema for iLocker - Neon PostgreSQL
-- =========================================================

-- =========================================================
-- 1. roles
-- =========================================================
CREATE TABLE IF NOT EXISTS roles (
    role_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name VARCHAR(50) NOT NULL UNIQUE,
    description TEXT
);

-- =========================================================
-- 2. users
-- =========================================================
CREATE TABLE IF NOT EXISTS users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id BIGINT NOT NULL,
    full_name VARCHAR(120) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    phone VARCHAR(20) UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'active',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_users_roles
        FOREIGN KEY (role_id)
        REFERENCES roles(role_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT chk_users_email_format
        CHECK (email ~* '^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$'),

    CONSTRAINT chk_users_phone_format
        CHECK (phone IS NULL OR phone ~ '^\+?[0-9]{9,15}$'),

    CONSTRAINT chk_users_status
        CHECK (status IN ('active', 'inactive', 'locked', 'deleted'))
);

-- =========================================================
-- 3. service_types
-- =========================================================
CREATE TABLE IF NOT EXISTS service_types (
    service_type_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_code VARCHAR(50) NOT NULL UNIQUE,
    service_name VARCHAR(150) NOT NULL,
    description TEXT,
    status VARCHAR(30) NOT NULL DEFAULT 'active',

    CONSTRAINT chk_service_types_code
        CHECK (service_code IN ('FULL_SERVICE', 'SELF_STORAGE', 'SMART_LOCKER')),

    CONSTRAINT chk_service_types_status
        CHECK (status IN ('active', 'inactive'))
);

-- =========================================================
-- 4. locations
-- =========================================================
CREATE TABLE IF NOT EXISTS locations (
    location_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location_name VARCHAR(150) NOT NULL,
    address TEXT NOT NULL,
    district VARCHAR(100),
    city VARCHAR(100) NOT NULL,
    latitude NUMERIC(10, 7),
    longitude NUMERIC(10, 7),
    open_time TIME,
    close_time TIME,
    is_24_7 BOOLEAN NOT NULL DEFAULT FALSE,
    status VARCHAR(30) NOT NULL DEFAULT 'active',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_locations_latitude
        CHECK (latitude IS NULL OR latitude BETWEEN -90 AND 90),

    CONSTRAINT chk_locations_longitude
        CHECK (longitude IS NULL OR longitude BETWEEN -180 AND 180),

    CONSTRAINT chk_locations_status
        CHECK (status IN ('active', 'inactive', 'maintenance')),

    CONSTRAINT chk_locations_open_close_time
        CHECK (
            is_24_7 = TRUE
            OR open_time IS NULL
            OR close_time IS NULL
            OR open_time < close_time
        )
);

-- =========================================================
-- 5. storage_sizes
-- =========================================================
CREATE TABLE IF NOT EXISTS storage_sizes (
    size_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_type_id BIGINT NOT NULL,
    size_code VARCHAR(50) NOT NULL,
    size_name VARCHAR(150) NOT NULL,
    volume_m3 NUMERIC(10, 2) NOT NULL,
    width_cm NUMERIC(10, 2),
    height_cm NUMERIC(10, 2),
    depth_cm NUMERIC(10, 2),
    base_price NUMERIC(15, 2) NOT NULL,
    description TEXT,
    status VARCHAR(30) NOT NULL DEFAULT 'active',

    CONSTRAINT fk_storage_sizes_service_types
        FOREIGN KEY (service_type_id)
        REFERENCES service_types(service_type_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT uq_storage_sizes_service_size_code
        UNIQUE (service_type_id, size_code),

    CONSTRAINT chk_storage_sizes_volume
        CHECK (volume_m3 > 0),

    CONSTRAINT chk_storage_sizes_dimensions
        CHECK (
            (width_cm IS NULL OR width_cm > 0)
            AND (height_cm IS NULL OR height_cm > 0)
            AND (depth_cm IS NULL OR depth_cm > 0)
        ),

    CONSTRAINT chk_storage_sizes_base_price
        CHECK (base_price >= 0),

    CONSTRAINT chk_storage_sizes_status
        CHECK (status IN ('active', 'inactive'))
);

-- =========================================================
-- 6. storage_units
-- =========================================================
CREATE TABLE IF NOT EXISTS storage_units (
    unit_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location_id BIGINT NOT NULL,
    size_id BIGINT NOT NULL,
    unit_code VARCHAR(80) NOT NULL,
    iot_device_id VARCHAR(120) UNIQUE,
    status VARCHAR(30) NOT NULL DEFAULT 'available',
    current_temperature NUMERIC(5, 2),
    current_humidity NUMERIC(5, 2),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_storage_units_locations
        FOREIGN KEY (location_id)
        REFERENCES locations(location_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_storage_units_storage_sizes
        FOREIGN KEY (size_id)
        REFERENCES storage_sizes(size_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT uq_storage_units_location_unit_code
        UNIQUE (location_id, unit_code),

    CONSTRAINT chk_storage_units_status
        CHECK (status IN ('available', 'reserved', 'occupied', 'maintenance', 'inactive')),

    CONSTRAINT chk_storage_units_temperature
        CHECK (current_temperature IS NULL OR current_temperature BETWEEN -20 AND 80),

    CONSTRAINT chk_storage_units_humidity
        CHECK (current_humidity IS NULL OR current_humidity BETWEEN 0 AND 100)
);

-- =========================================================
-- 7. duration_options
-- =========================================================
CREATE TABLE IF NOT EXISTS duration_options (
    duration_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    duration_name VARCHAR(100) NOT NULL UNIQUE,
    duration_months NUMERIC(8, 2) NOT NULL,
    multiplier NUMERIC(8, 2) NOT NULL,
    description TEXT,
    status VARCHAR(30) NOT NULL DEFAULT 'active',

    CONSTRAINT chk_duration_options_months
        CHECK (duration_months > 0),

    CONSTRAINT chk_duration_options_multiplier
        CHECK (multiplier > 0),

    CONSTRAINT chk_duration_options_status
        CHECK (status IN ('active', 'inactive'))
);

-- =========================================================
-- 8. protection_plans
-- =========================================================
CREATE TABLE IF NOT EXISTS protection_plans (
    protection_plan_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_name VARCHAR(100) NOT NULL UNIQUE,
    monthly_price NUMERIC(15, 2) NOT NULL DEFAULT 0,
    coverage_description TEXT,
    status VARCHAR(30) NOT NULL DEFAULT 'active',

    CONSTRAINT chk_protection_plans_monthly_price
        CHECK (monthly_price >= 0),

    CONSTRAINT chk_protection_plans_status
        CHECK (status IN ('active', 'inactive'))
);

-- =========================================================
-- 9. addon_services
-- =========================================================
CREATE TABLE IF NOT EXISTS addon_services (
    addon_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    addon_code VARCHAR(50) NOT NULL UNIQUE,
    addon_name VARCHAR(150) NOT NULL,
    pricing_type VARCHAR(50) NOT NULL,
    base_price NUMERIC(15, 2) NOT NULL DEFAULT 0,
    extra_price NUMERIC(15, 2) NOT NULL DEFAULT 0,
    free_threshold INT NOT NULL DEFAULT 0,
    unit_name VARCHAR(50),
    description TEXT,
    status VARCHAR(30) NOT NULL DEFAULT 'active',

    CONSTRAINT chk_addon_services_pricing_type
        CHECK (pricing_type IN ('fixed', 'per_km', 'per_box', 'mixed')),

    CONSTRAINT chk_addon_services_prices
        CHECK (base_price >= 0 AND extra_price >= 0),

    CONSTRAINT chk_addon_services_free_threshold
        CHECK (free_threshold >= 0),

    CONSTRAINT chk_addon_services_status
        CHECK (status IN ('active', 'inactive'))
);

-- =========================================================
-- 10. rental_orders
-- =========================================================
CREATE TABLE IF NOT EXISTS rental_orders (
    order_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    service_type_id BIGINT NOT NULL,
    location_id BIGINT NOT NULL,
    order_code VARCHAR(80) NOT NULL UNIQUE,
    order_status VARCHAR(50) NOT NULL DEFAULT 'pending_payment',
    storage_fee NUMERIC(15, 2) NOT NULL DEFAULT 0,
    protection_fee NUMERIC(15, 2) NOT NULL DEFAULT 0,
    addon_fee NUMERIC(15, 2) NOT NULL DEFAULT 0,
    discount_amount NUMERIC(15, 2) NOT NULL DEFAULT 0,
    total_amount NUMERIC(15, 2) NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_rental_orders_users
        FOREIGN KEY (user_id)
        REFERENCES users(user_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_rental_orders_service_types
        FOREIGN KEY (service_type_id)
        REFERENCES service_types(service_type_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_rental_orders_locations
        FOREIGN KEY (location_id)
        REFERENCES locations(location_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT chk_rental_orders_status
        CHECK (order_status IN (
            'pending_payment',
            'paid',
            'active',
            'completed',
            'cancelled',
            'failed'
        )),

    CONSTRAINT chk_rental_orders_amounts
        CHECK (
            storage_fee >= 0
            AND protection_fee >= 0
            AND addon_fee >= 0
            AND discount_amount >= 0
            AND total_amount >= 0
        )
);

-- =========================================================
-- 11. rental_order_items
-- =========================================================
CREATE TABLE IF NOT EXISTS rental_order_items (
    item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    unit_id BIGINT NOT NULL,
    size_id BIGINT NOT NULL,
    duration_id BIGINT NOT NULL,
    protection_plan_id BIGINT NOT NULL,
    start_time TIMESTAMPTZ NOT NULL,
    end_time TIMESTAMPTZ NOT NULL,
    base_price NUMERIC(15, 2) NOT NULL,
    duration_multiplier NUMERIC(8, 2) NOT NULL,
    storage_fee NUMERIC(15, 2) NOT NULL DEFAULT 0,
    protection_fee NUMERIC(15, 2) NOT NULL DEFAULT 0,
    item_status VARCHAR(50) NOT NULL DEFAULT 'pending',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_rental_order_items_orders
        FOREIGN KEY (order_id)
        REFERENCES rental_orders(order_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_rental_order_items_units
        FOREIGN KEY (unit_id)
        REFERENCES storage_units(unit_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_rental_order_items_sizes
        FOREIGN KEY (size_id)
        REFERENCES storage_sizes(size_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_rental_order_items_durations
        FOREIGN KEY (duration_id)
        REFERENCES duration_options(duration_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_rental_order_items_protection_plans
        FOREIGN KEY (protection_plan_id)
        REFERENCES protection_plans(protection_plan_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT uq_rental_order_items_order_unit
        UNIQUE (order_id, unit_id),

    CONSTRAINT chk_rental_order_items_time
        CHECK (end_time > start_time),

    CONSTRAINT chk_rental_order_items_price
        CHECK (
            base_price >= 0
            AND duration_multiplier > 0
            AND storage_fee >= 0
            AND protection_fee >= 0
        ),

    CONSTRAINT chk_rental_order_items_status
        CHECK (item_status IN ('pending', 'reserved', 'active', 'completed', 'cancelled'))
);

-- =========================================================
-- 12. order_addons
-- =========================================================
CREATE TABLE IF NOT EXISTS order_addons (
    order_addon_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    addon_id BIGINT NOT NULL,
    quantity INT NOT NULL DEFAULT 1,
    distance_km NUMERIC(10, 2) NOT NULL DEFAULT 0,
    box_count INT NOT NULL DEFAULT 0,
    unit_price NUMERIC(15, 2) NOT NULL DEFAULT 0,
    total_price NUMERIC(15, 2) NOT NULL DEFAULT 0,

    CONSTRAINT fk_order_addons_orders
        FOREIGN KEY (order_id)
        REFERENCES rental_orders(order_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_order_addons_addon_services
        FOREIGN KEY (addon_id)
        REFERENCES addon_services(addon_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT uq_order_addons_order_addon
        UNIQUE (order_id, addon_id),

    CONSTRAINT chk_order_addons_numbers
        CHECK (
            quantity > 0
            AND distance_km >= 0
            AND box_count >= 0
            AND unit_price >= 0
            AND total_price >= 0
        )
);

-- =========================================================
-- 13. payments
-- =========================================================
CREATE TABLE IF NOT EXISTS payments (
    payment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    payment_method VARCHAR(50) NOT NULL,
    payment_provider VARCHAR(80) NOT NULL,
    amount NUMERIC(15, 2) NOT NULL,
    currency VARCHAR(10) NOT NULL DEFAULT 'VND',
    payment_status VARCHAR(50) NOT NULL DEFAULT 'pending',
    provider_transaction_id VARCHAR(150),
    paid_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_payments_orders
        FOREIGN KEY (order_id)
        REFERENCES rental_orders(order_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT uq_payments_provider_transaction
        UNIQUE (payment_provider, provider_transaction_id),

    CONSTRAINT chk_payments_amount
        CHECK (amount >= 0),

    CONSTRAINT chk_payments_currency
        CHECK (currency IN ('VND', 'USD')),

    CONSTRAINT chk_payments_method
        CHECK (payment_method IN ('cash', 'bank_transfer', 'card', 'momo', 'vnpay', 'zalopay')),

    CONSTRAINT chk_payments_status
        CHECK (payment_status IN ('pending', 'success', 'failed', 'cancelled', 'refunded'))
);

-- =========================================================
-- 14. payment_webhooks
-- =========================================================
CREATE TABLE IF NOT EXISTS payment_webhooks (
    webhook_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_id BIGINT NOT NULL,
    provider_name VARCHAR(80) NOT NULL,
    event_type VARCHAR(100) NOT NULL,
    raw_payload JSONB NOT NULL,
    received_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    processed_status VARCHAR(50) NOT NULL DEFAULT 'pending',

    CONSTRAINT fk_payment_webhooks_payments
        FOREIGN KEY (payment_id)
        REFERENCES payments(payment_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT chk_payment_webhooks_processed_status
        CHECK (processed_status IN ('pending', 'processed', 'failed', 'ignored'))
);

-- =========================================================
-- 15. rentals
-- =========================================================
CREATE TABLE IF NOT EXISTS rentals (
    rental_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    item_id BIGINT NOT NULL UNIQUE,
    user_id BIGINT NOT NULL,
    unit_id BIGINT NOT NULL,
    rental_code VARCHAR(80) NOT NULL UNIQUE,
    actual_start_time TIMESTAMPTZ NOT NULL,
    expected_end_time TIMESTAMPTZ NOT NULL,
    actual_end_time TIMESTAMPTZ,
    rental_status VARCHAR(50) NOT NULL DEFAULT 'active',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_rentals_orders
        FOREIGN KEY (order_id)
        REFERENCES rental_orders(order_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_rentals_items
        FOREIGN KEY (item_id)
        REFERENCES rental_order_items(item_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_rentals_users
        FOREIGN KEY (user_id)
        REFERENCES users(user_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_rentals_units
        FOREIGN KEY (unit_id)
        REFERENCES storage_units(unit_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT chk_rentals_time
        CHECK (
            expected_end_time > actual_start_time
            AND (actual_end_time IS NULL OR actual_end_time >= actual_start_time)
        ),

    CONSTRAINT chk_rentals_status
        CHECK (rental_status IN ('active', 'overdue', 'completed', 'cancelled'))
);

-- =========================================================
-- 16. access_credentials
-- =========================================================
CREATE TABLE IF NOT EXISTS access_credentials (
    credential_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rental_id BIGINT NOT NULL,
    credential_type VARCHAR(30) NOT NULL,
    credential_value VARCHAR(255) NOT NULL UNIQUE,
    expired_at TIMESTAMPTZ NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_access_credentials_rentals
        FOREIGN KEY (rental_id)
        REFERENCES rentals(rental_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT chk_access_credentials_type
        CHECK (credential_type IN ('QR', 'OTP', 'PIN')),

    CONSTRAINT chk_access_credentials_expired_at
        CHECK (expired_at > created_at)
);

-- =========================================================
-- 17. unit_access_logs
-- =========================================================
CREATE TABLE IF NOT EXISTS unit_access_logs (
    access_log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rental_id BIGINT NOT NULL,
    unit_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    action_type VARCHAR(50) NOT NULL,
    action_result VARCHAR(50) NOT NULL,
    event_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    note TEXT,

    CONSTRAINT fk_unit_access_logs_rentals
        FOREIGN KEY (rental_id)
        REFERENCES rentals(rental_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_unit_access_logs_units
        FOREIGN KEY (unit_id)
        REFERENCES storage_units(unit_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_unit_access_logs_users
        FOREIGN KEY (user_id)
        REFERENCES users(user_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT chk_unit_access_logs_action_type
        CHECK (action_type IN ('unlock', 'lock', 'check_in', 'check_out')),

    CONSTRAINT chk_unit_access_logs_action_result
        CHECK (action_result IN ('success', 'failed'))
);

-- =========================================================
-- 18. support_tickets
-- =========================================================
CREATE TABLE IF NOT EXISTS support_tickets (
    ticket_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    order_id BIGINT,
    rental_id BIGINT,
    assigned_staff_id BIGINT,
    subject VARCHAR(200) NOT NULL,
    category VARCHAR(80) NOT NULL,
    priority VARCHAR(30) NOT NULL DEFAULT 'normal',
    ticket_status VARCHAR(50) NOT NULL DEFAULT 'open',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_support_tickets_users
        FOREIGN KEY (user_id)
        REFERENCES users(user_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_support_tickets_orders
        FOREIGN KEY (order_id)
        REFERENCES rental_orders(order_id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT fk_support_tickets_rentals
        FOREIGN KEY (rental_id)
        REFERENCES rentals(rental_id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT fk_support_tickets_assigned_staff
        FOREIGN KEY (assigned_staff_id)
        REFERENCES users(user_id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT chk_support_tickets_priority
        CHECK (priority IN ('low', 'normal', 'high', 'urgent')),

    CONSTRAINT chk_support_tickets_status
        CHECK (ticket_status IN ('open', 'assigned', 'in_progress', 'resolved', 'closed', 'cancelled'))
);

-- =========================================================
-- 19. support_messages
-- =========================================================
CREATE TABLE IF NOT EXISTS support_messages (
    message_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id BIGINT NOT NULL,
    sender_id BIGINT NOT NULL,
    message_content TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_support_messages_tickets
        FOREIGN KEY (ticket_id)
        REFERENCES support_tickets(ticket_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_support_messages_senders
        FOREIGN KEY (sender_id)
        REFERENCES users(user_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);

-- =========================================================
-- 20. notifications
-- =========================================================
CREATE TABLE IF NOT EXISTS notifications (
    notification_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    order_id BIGINT,
    rental_id BIGINT,
    notification_type VARCHAR(80) NOT NULL,
    title VARCHAR(200) NOT NULL,
    content TEXT NOT NULL,
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_notifications_users
        FOREIGN KEY (user_id)
        REFERENCES users(user_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_notifications_orders
        FOREIGN KEY (order_id)
        REFERENCES rental_orders(order_id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT fk_notifications_rentals
        FOREIGN KEY (rental_id)
        REFERENCES rentals(rental_id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT chk_notifications_type
        CHECK (notification_type IN (
            'payment_success',
            'payment_failed',
            'rental_started',
            'rental_expiring',
            'rental_overdue',
            'credential_created',
            'ticket_replied',
            'system'
        ))
);

-- =========================================================
-- 21. audit_logs
-- =========================================================
CREATE TABLE IF NOT EXISTS audit_logs (
    audit_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_id BIGINT NOT NULL,
    action VARCHAR(100) NOT NULL,
    entity_name VARCHAR(100) NOT NULL,
    entity_id BIGINT NOT NULL,
    ip_address VARCHAR(60),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_audit_logs_actor
        FOREIGN KEY (actor_id)
        REFERENCES users(user_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);

-- =========================================================
-- Indexes for common queries
-- =========================================================

CREATE INDEX IF NOT EXISTS idx_users_role_id
    ON users(role_id);

CREATE INDEX IF NOT EXISTS idx_storage_sizes_service_type_id
    ON storage_sizes(service_type_id);

CREATE INDEX IF NOT EXISTS idx_storage_units_location_id
    ON storage_units(location_id);

CREATE INDEX IF NOT EXISTS idx_storage_units_size_id
    ON storage_units(size_id);

CREATE INDEX IF NOT EXISTS idx_storage_units_status
    ON storage_units(status);

CREATE INDEX IF NOT EXISTS idx_rental_orders_user_id
    ON rental_orders(user_id);

CREATE INDEX IF NOT EXISTS idx_rental_orders_status
    ON rental_orders(order_status);

CREATE INDEX IF NOT EXISTS idx_rental_orders_created_at
    ON rental_orders(created_at);

CREATE INDEX IF NOT EXISTS idx_rental_order_items_order_id
    ON rental_order_items(order_id);

CREATE INDEX IF NOT EXISTS idx_rental_order_items_unit_id
    ON rental_order_items(unit_id);

CREATE INDEX IF NOT EXISTS idx_order_addons_order_id
    ON order_addons(order_id);

CREATE INDEX IF NOT EXISTS idx_payments_order_id
    ON payments(order_id);

CREATE INDEX IF NOT EXISTS idx_payments_status
    ON payments(payment_status);

CREATE INDEX IF NOT EXISTS idx_payment_webhooks_payment_id
    ON payment_webhooks(payment_id);

CREATE INDEX IF NOT EXISTS idx_rentals_order_id
    ON rentals(order_id);

CREATE INDEX IF NOT EXISTS idx_rentals_user_id
    ON rentals(user_id);

CREATE INDEX IF NOT EXISTS idx_rentals_unit_id
    ON rentals(unit_id);

CREATE INDEX IF NOT EXISTS idx_rentals_status
    ON rentals(rental_status);

CREATE INDEX IF NOT EXISTS idx_access_credentials_rental_id
    ON access_credentials(rental_id);

CREATE INDEX IF NOT EXISTS idx_unit_access_logs_rental_id
    ON unit_access_logs(rental_id);

CREATE INDEX IF NOT EXISTS idx_unit_access_logs_unit_id
    ON unit_access_logs(unit_id);

CREATE INDEX IF NOT EXISTS idx_unit_access_logs_user_id
    ON unit_access_logs(user_id);

CREATE INDEX IF NOT EXISTS idx_unit_access_logs_event_time
    ON unit_access_logs(event_time);

CREATE INDEX IF NOT EXISTS idx_support_tickets_user_id
    ON support_tickets(user_id);

CREATE INDEX IF NOT EXISTS idx_support_tickets_assigned_staff_id
    ON support_tickets(assigned_staff_id);

CREATE INDEX IF NOT EXISTS idx_support_tickets_status
    ON support_tickets(ticket_status);

CREATE INDEX IF NOT EXISTS idx_support_messages_ticket_id
    ON support_messages(ticket_id);

CREATE INDEX IF NOT EXISTS idx_notifications_user_id
    ON notifications(user_id);

CREATE INDEX IF NOT EXISTS idx_notifications_is_read
    ON notifications(is_read);

CREATE INDEX IF NOT EXISTS idx_audit_logs_actor_id
    ON audit_logs(actor_id);

CREATE INDEX IF NOT EXISTS idx_audit_logs_entity
    ON audit_logs(entity_name, entity_id);

COMMIT;