/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "inverse-on-surface": "#e0f4ff",
        "primary": "#00113a",
        "primary-fixed-dim": "#b3c5ff",
        "tertiary-fixed-dim": "#c4c7ca",
        "on-tertiary-fixed-variant": "#44474a",
        "surface-container-highest": "#c9e7f7",
        "surface": "#f4faff",
        "on-primary-container": "#758dd5",
        "surface-bright": "#f4faff",
        "secondary-fixed": "#9cf0ff",
        "on-error-container": "#93000a",
        "error-container": "#ffdad6",
        "surface-dim": "#c0dfee",
        "outline-variant": "#c5c6d2",
        "tertiary-container": "#26292b",
        "surface-tint": "#435b9f",
        "on-surface": "#001f2a",
        "secondary-fixed-dim": "#00daf3",
        "outline": "#757682",
        "on-surface-variant": "#444650",
        "surface-variant": "#c9e7f7",
        "background": "#f4faff",
        "on-background": "#001f2a",
        "primary-container": "#002366",
        "secondary-container": "#00e3fd",
        "on-primary-fixed": "#00174a",
        "tertiary": "#111517",
        "on-secondary-container": "#00616d",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed-variant": "#2a4386",
        "on-secondary-fixed-variant": "#004f58",
        "surface-container-low": "#e6f6ff",
        "inverse-primary": "#b3c5ff",
        "on-tertiary-container": "#8d9093",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed": "#191c1e",
        "primary-fixed": "#dbe1ff",
        "surface-container": "#d9f2ff",
        "inverse-surface": "#163440",
        "tertiary-fixed": "#e0e3e6",
        "on-secondary": "#ffffff",
        "on-error": "#ffffff",
        "secondary": "#006875",
        "on-secondary-fixed": "#001f24",
        "surface-container-high": "#ceedfd",
        "on-primary": "#ffffff",
        "error": "#ba1a1a"
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
}